### ISSUE TITLE
Discuss and Decide on Tree Data Structure format

### ISSUE THREAD

**Issue by Restuta** [Ingenio/keen-teamcity-logs-parser#1]
Before we make hard decisions about tree structure lets discuss what are our options, I see two ways to go with it:

* create an abstract tree structure that make sense for us and then convert it to D3 format (I am leaning towards this)
* create D3-specific structure

**Comment by AlexanderKapelyukhovskiy** [comment]
As I can see from https://github.com/spiermar/d3-flame-graph
they provide following node format:
```
{
  "name": "<name>",
  "value": <value>,
  "children": [
    <Object>
  ]
}
```
we can use same but for easies tree build process can also add link to parent element.

**Comment by AlexanderKapelyukhovskiy** [comment]
I think we even can simply map our `LogEntry` item which contains log message, log date, child and parent to D3 item without parent property. 
Log message could be D3 property name and with help of log date we could calculate log values as time difference from previous log entry

**Comment by Restuta** [comment]
I am leaning towards our own format that we can convert to theirs, something like:
for the node:
```
{
  id: <unique identificator of a node>
  name: "node-name",
  value: "node-value",
  children: [],
  parent: <obj>,
  _parentRef: <id of the parent node>
}
```

for the tree type:
```
{
   __root: <root node>
<in future methods for traversal> 
}
```

### Serialization 
Tree should be serializable to JSON, which could be tricky with "parent" circular relationship, we would need to investigate that, since we need to store parsed logs. If we can serialize it we may not be able to de-serialize it. Quickest workaround that comes to mind is to have a `_parentRef` internal property that would help to materialize the nodes, but that would require an additional tree-traversal after serialization (which is fine)

**Comment by AlexanderKapelyukhovskiy** [comment]
@Restuta please review my last commit. It looks it is working. Next step could be D3 integration, bug fixes and optimization

**Comment by Restuta** [comment]
@AlexanderKapelyukhovskiy not sure how serialization of parents works there, can you clarify?

**Comment by Restuta** [comment]
so no parent for now, okay
